### ISSUE TITLE
このレポジトリの説明欄に書いてある「リポジトリはお引越ししました。」の先の URL が間違っています

### ISSUE THREAD

**Issue by kmyk** [earlgray283/JUDGE_SYSTEM#3]
ところで GitHub にはレポジトリ名変更という機能があり、これを使えば自動でリダイレクトまでしてくれたはずなのでおすすめです

**Comment by earlgray283** [comment]
コミットの数がえげつなかったのでリポジトリを新しくしました。
また引越しする機会があったら使ってみます。ありがとうございます

**Comment by kmyk** [comment]
(ところでコミット数 1000 はまだまだ少ないのであまり気にしなくてよさそうです。たとえば https://github.com/python/cpython と比較すると桁が 2 つ足りません。)

**Comment by earlgray283** [comment]
えぇ...
まあ、この1000コミットはgithubの使い方完全に間違えていた結果でしたから良しとしますw(なぜかバックアップとして使っていた)
